import type { ServiceCategory, ServiceProvider } from "../types";

export const MOCK_CATEGORIES: ServiceCategory[] = [
  { id: "repairing", name: "Repairing", icon: "🔧" },
  { id: "electricity", name: "Electricity", icon: "⚡" },
  { id: "plumbing", name: "Plumbing", icon: "🔩" },
  { id: "cleaning", name: "Cleaning", icon: "🧹" },
  { id: "excavation", name: "Excavation", icon: "⛏️" },
  { id: "painting", name: "Painting", icon: "🖌️" },
  { id: "hvac", name: "HVAC", icon: "❄️" },
  { id: "roofing", name: "Roofing", icon: "🏠" },
  { id: "landscaping", name: "Landscaping", icon: "🌿" },
  { id: "locksmith", name: "Locksmith", icon: "🔑" },
  { id: "pest_control", name: "Pest Control", icon: "🐛" },
  { id: "appliances", name: "Appliances", icon: "🫧" },
];

export const MOCK_PROVIDERS: ServiceProvider[] = [
  {
    id: "1",
    name: "Marcus Rivera",
    category: "plumbing",
    rating: 5.0,
    reviewCount: 148,
    hourlyRate: 85,
    available: true,
    location: "Brooklyn, NY",
    distanceMiles: 1.2,
    imageUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400&q=80",
    specialties: ["Leak Repair", "Pipe Installation", "Water Heater"],
  },
  {
    id: "2",
    name: "Darnell Thompson",
    category: "electricity",
    rating: 4.5,
    reviewCount: 203,
    hourlyRate: 95,
    available: true,
    location: "Manhattan, NY",
    distanceMiles: 2.4,
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&q=80",
    specialties: ["Panel Upgrades", "Wiring", "Smart Home"],
  },
  {
    id: "3",
    name: "Sofia Chen",
    category: "cleaning",
    rating: 4.8,
    reviewCount: 312,
    hourlyRate: 55,
    available: false,
    location: "Queens, NY",
    distanceMiles: 3.1,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
    specialties: ["Deep Clean", "Post-Construction", "Move-In/Out"],
  },
  {
    id: "4",
    name: "James O'Brien",
    category: "repairing",
    rating: 4.7,
    reviewCount: 89,
    hourlyRate: 75,
    available: true,
    location: "Bronx, NY",
    distanceMiles: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=400&q=80",
    specialties: ["Appliance Repair", "Drywall", "Carpentry"],
  },
  {
    id: "5",
    name: "Priya Patel",
    category: "painting",
    rating: 4.9,
    reviewCount: 176,
    hourlyRate: 65,
    available: true,
    location: "Staten Island, NY",
    distanceMiles: 5.8,
    imageUrl: "https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400&q=80",
    specialties: ["Interior", "Exterior", "Cabinet Refinishing"],
  },
  {
    id: "6",
    name: "Carlos Mendez",
    category: "hvac",
    rating: 4.6,
    reviewCount: 134,
    hourlyRate: 110,
    available: true,
    location: "Jersey City, NJ",
    distanceMiles: 6.2,
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80",
    specialties: ["AC Install", "Furnace Repair", "Duct Cleaning"],
  },
  {
    id: "7",
    name: "Aaliyah Washington",
    category: "cleaning",
    rating: 4.9,
    reviewCount: 421,
    hourlyRate: 60,
    available: true,
    location: "Harlem, NY",
    distanceMiles: 1.8,
    imageUrl: "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&q=80",
    specialties: ["Residential", "Office Cleaning", "Eco-Friendly"],
  },
  {
    id: "8",
    name: "Trevor Kim",
    category: "roofing",
    rating: 4.7,
    reviewCount: 67,
    hourlyRate: 130,
    available: true,
    location: "Long Island, NY",
    distanceMiles: 7.3,
    imageUrl: "https://images.unsplash.com/photo-1590588110761-6dc87a5e84cf?w=400&q=80",
    specialties: ["Shingle Replacement", "Flat Roof", "Leak Sealing"],
  },
  {
    id: "9",
    name: "Elena Vasquez",
    category: "landscaping",
    rating: 4.8,
    reviewCount: 95,
    hourlyRate: 70,
    available: false,
    location: "Hoboken, NJ",
    distanceMiles: 4.1,
    imageUrl: "https://images.unsplash.com/photo-1607400201515-c2c41c07d307?w=400&q=80",
    specialties: ["Lawn Care", "Garden Design", "Tree Trimming"],
  },
  {
    id: "10",
    name: "DeShawn Harris",
    category: "locksmith",
    rating: 4.9,
    reviewCount: 211,
    hourlyRate: 80,
    available: true,
    location: "Williamsburg, NY",
    distanceMiles: 2.0,
    imageUrl: "https://images.unsplash.com/photo-1611605698335-8b1569810432?w=400&q=80",
    specialties: ["Lock Replacement", "Emergency Lockout", "Smart Locks"],
  },
  {
    id: "11",
    name: "Fatima Al-Hassan",
    category: "electricity",
    rating: 4.6,
    reviewCount: 158,
    hourlyRate: 90,
    available: true,
    location: "Astoria, NY",
    distanceMiles: 3.5,
    imageUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&q=80",
    specialties: ["EV Charger Install", "Lighting", "Generator"],
  },
  {
    id: "12",
    name: "Bobby Nguyen",
    category: "pest_control",
    rating: 4.5,
    reviewCount: 73,
    hourlyRate: 120,
    available: true,
    location: "Flushing, NY",
    distanceMiles: 5.0,
    imageUrl: "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=400&q=80",
    specialties: ["Rodents", "Bed Bugs", "Cockroaches", "Termites"],
  },
  {
    id: "13",
    name: "Natalie Brooks",
    category: "appliances",
    rating: 4.8,
    reviewCount: 184,
    hourlyRate: 85,
    available: false,
    location: "Upper West Side, NY",
    distanceMiles: 2.7,
    imageUrl: "https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=400&q=80",
    specialties: ["Washer/Dryer", "Refrigerator", "Dishwasher"],
  },
  {
    id: "14",
    name: "Ahmed Okafor",
    category: "plumbing",
    rating: 4.4,
    reviewCount: 52,
    hourlyRate: 78,
    available: true,
    location: "Crown Heights, NY",
    distanceMiles: 3.9,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80",
    specialties: ["Drain Cleaning", "Bathroom Install", "Sewer Line"],
  },
  {
    id: "15",
    name: "Rachel Goldstein",
    category: "painting",
    rating: 5.0,
    reviewCount: 240,
    hourlyRate: 72,
    available: true,
    location: "Park Slope, NY",
    distanceMiles: 2.2,
    imageUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&q=80",
    specialties: ["Faux Finishes", "Murals", "Interior Walls"],
  },
  {
    id: "16",
    name: "Tony Petrov",
    category: "excavation",
    rating: 4.3,
    reviewCount: 38,
    hourlyRate: 150,
    available: true,
    location: "Newark, NJ",
    distanceMiles: 9.5,
    imageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&q=80",
    specialties: ["Foundation Work", "Trenching", "Site Prep"],
  },
  {
    id: "17",
    name: "Maria Santos",
    category: "hvac",
    rating: 4.7,
    reviewCount: 119,
    hourlyRate: 105,
    available: false,
    location: "Sunset Park, NY",
    distanceMiles: 4.8,
    imageUrl: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&q=80",
    specialties: ["Mini-Split Install", "Duct Sealing", "Thermostat Setup"],
  },
  {
    id: "18",
    name: "Isaiah Grant",
    category: "repairing",
    rating: 4.6,
    reviewCount: 107,
    hourlyRate: 70,
    available: true,
    location: "Flatbush, NY",
    distanceMiles: 1.5,
    imageUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
    specialties: ["Tile Work", "Door Repair", "Window Installation"],
  },
];

export const formatCurrency = (amount: number): string =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
  }).format(amount);

export const getStatusLabel = (status: string): string => {
  const labels: Record<string, string> = {
    pending: "Pending",
    accepted: "Accepted",
    en_route: "En Route",
    in_progress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
  };
  return labels[status] ?? status;
};

export const getStatusColor = (status: string): string => {
  const colors: Record<string, string> = {
    pending: "#f59e0b",
    accepted: "#3b82f6",
    en_route: "#8b5cf6",
    in_progress: "#10b981",
    completed: "#6b7280",
    cancelled: "#ef4444",
  };
  return colors[status] ?? "#6b7280";
};
